# Generated by Django 5.2.1 on 2025-06-05 07:59

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_image_property_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
