# Generated by Django 5.2.1 on 2025-06-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_4',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
