# Generated by Django 5.2.1 on 2025-06-05 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_image_2_remove_property_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
