# Generated by Django 5.2.1 on 2025-06-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
