# Generated by Django 5.2.1 on 2025-06-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'À vendre'), ('rent', 'À louer')], default='sale', max_length=10),
        ),
    ]
