# Generated by Django 5.2.1 on 2025-06-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'À vendre'), ('rent', 'À louer')], default='rent', max_length=10),
        ),
    ]
