# Generated by Django 5.2.1 on 2025-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='has_electricity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_water',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
