# Generated by Django 5.2.1 on 2025-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_title_remove_property_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='title',
        ),
    ]
