# Generated by Django 5.2.1 on 2025-06-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_title_alter_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='PropertyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertytype'),
        ),
    ]
